import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:ideaspark/view_models/locale_view_model.dart';

/// Traductions statiques FR/EN (sans API). Utiliser [context.tr(key)].
class AppLocalizations {
  AppLocalizations._();

  static const Map<String, String> _fr = {
    // App
    'app_name': 'IdeaSpark',
    'splash_tagline': 'Génère · Teste · Lance',

    // Auth
    'login': 'Connexion',
    'signup': 'Créer un compte',
    'email': 'Email',
    'email_hint': 'votre@email.com',
    'password': 'Mot de passe',
    'password_hint': '••••••••',
    'confirm_password': 'Confirmer le mot de passe',
    'sign_in': 'Se connecter',
    'sign_up': 'S\'inscrire',
    'or': 'ou',
    'continue_google': 'Continuer avec Google',
    'continue_facebook': 'Continuer avec Facebook',
    'signup_google': 'S\'inscrire avec Google',
    'signup_facebook': 'S\'inscrire avec Facebook',
    'no_account': 'Pas de compte ? ',
    'has_account': 'Déjà un compte ? ',
    'verify_email_title': 'Vérifiez votre email',
    'verify_email_sent': 'Un code à 6 chiffres a été envoyé à',
    'verify_code_hint': 'Code de vérification',
    'forgot_password': 'Mot de passe oublié',
    'forgot_password_enter_email': 'Entrez votre email pour recevoir un code de réinitialisation.',
    'forgot_password_send_code': 'Envoyer le code',
    'forgot_password_code_sent': 'Code envoyé à votre email.',
    'forgot_password_code_sent_to': 'Un code a été envoyé à',
    'reset_password': 'Réinitialiser le mot de passe',
    'password_reset_success': 'Mot de passe mis à jour. Connectez-vous avec votre nouveau mot de passe.',
    'back_to_login': 'Retour à la connexion',
    'new_password': 'Nouveau mot de passe',
    'current_password': 'Mot de passe actuel',
    'change_password': 'Changer le mot de passe',
    'change_password_title': 'Changer le mot de passe',
    'change_password_confirm': 'Enregistrer',
    'change_password_success': 'Mot de passe mis à jour.',
    'passwords_do_not_match': 'Les mots de passe ne correspondent pas.',
    'verify_button': 'Vérifier',
    'resend_code': 'Renvoyer le code',

    // Onboarding
    'onboarding_title_1': 'Des idées instantanées',
    'onboarding_desc_1': 'Générateur intelligent pour créer des concepts de business, vidéos, produits et slogans en quelques secondes.',
    'onboarding_title_2': 'Filtre par niche et audience',
    'onboarding_desc_2': 'Personnalise chaque génération selon ton marché cible, ton audience et tes objectifs spécifiques.',
    'onboarding_title_3': 'Sauvegarde et re-génère',
    'onboarding_desc_3': 'Garde tes meilleures idées, crée des variations et partage-les avec ton équipe.',
    'start': 'COMMENCER',
    'continue': 'CONTINUER',
    'skip': 'Passer',

    // Home
    'hello': 'Bonjour 👋',
    'what_idea_type': 'Quel type d\'idée veux-tu générer ?',
    'trends': 'Tendances',
    'see_all': 'Voir tout',
    'library_saved': 'Bibliothèque · Mes idées sauvegardées',
    'nav_home': 'Accueil',
    'nav_favorites': 'Favoris',
    'nav_history': 'Historique',
    'nav_profile': 'Profil',

    // Home generators (titles)
    'gen_business': 'Business Ideas',
    'gen_video': 'Video Ideas',
    'gen_product': 'Product Ideas',
    'gen_slogans': 'Slogans & Names',

    // Criteria
    'settings': 'Paramètres',
    'tell_us_what': 'Dis-nous quoi générer',
    'type': 'Type',
    'niche': 'Niche',
    'niche_hint': 'Ex: Fitness, Beauty, Tech...',
    'target_audience': 'Audience cible',
    'platform': 'Plateforme',
    'tone_style': 'Ton / Style',
    'creativity_level': 'Niveau Créativité',
    'realistic': 'Réaliste',
    'creative': 'Créatif',
    'generate_10': 'Générer 10 idées',
    'surprise_me': 'Surprise me ✨',

    // Criteria options (for trOption)
    'opt_étudiants': 'Étudiants',
    'opt_mamans': 'Mamans',
    'opt_entrepreneurs': 'Entrepreneurs',
    'opt_freelancers': 'Freelancers',
    'opt_tiktok': 'TikTok',
    'opt_reels': 'Reels',
    'opt_youtube': 'YouTube',
    'opt_shorts': 'Shorts',
    'opt_viral': 'Viral',
    'opt_premium': 'Premium',
    'opt_fun': 'Fun',
    'opt_sérieux': 'Sérieux',
    'filter_all': 'Tous',
    'filter_viral': 'Viral',
    'filter_realistic': 'Réaliste',
    'filter_short': 'Courtes',
    'filter_business': 'Business',
    'filter_video': 'Video',
    'favorites_title': 'Favoris',
    'history_title': 'Historique',

    // Video form
    'new_video_idea': 'Nouvelle Idée Vidéo',
    'theme_niche': 'Thématique / Niche *',
    'theme_hint': 'Ex: Fitness, Tech, Cuisine...',
    'target_platform': 'Plateforme cible',
    'duration': 'Durée souhaitée',
    'keywords_optional': 'Mots-clés (optionnel)',
    'keywords_hint': 'Séparez par des virgules',
    'generate_ideas': '✨ Générer des Idées',
    'platform_youtube': 'YouTube',
    'platform_tiktok': 'TikTok',
    'platform_reels': 'Instagram Reels',
    'platform_shorts': 'YouTube Shorts',
    'duration_short': 'Court (<1min)',
    'duration_medium': 'Moyen (3-5min)',
    'duration_long': 'Long (10min+)',
    'tone_educational': 'Éducatif',
    'tone_entertaining': 'Divertissant',
    'tone_inspiring': 'Inspirant',
    'tone_commercial': 'Commercial',

    // Gemini 2.0 Features
    'smart_analysis': 'Analyse Intelligente',
    'image_picker_desc': 'Prenez en photo votre produit pour remplir automatiquement les champs ci-dessous.',
    'gallery': 'Galerie',
    'camera': 'Appareil',
    'analyzing': 'Analyse en cours...',
    'refine_hint': 'Affiner cette idée...',
    'remaining_tries': 'essais restants',
    'limit_reached': 'Limite de raffinements atteinte',
    'approve': 'Approuver',
    'version': 'Version',
    'version_history': 'HISTORIQUE DES VERSIONS',
    'suggested_locations': 'LIEUX DE TOURNAGE SUGGÉRÉS',
    'refine_error': 'Échec du raffinement. Veuillez réessayer.',
    'approve_error': 'Échec de l\'approbation.',
    'refine_limit_error': 'Nombre maximum de raffinements atteint (3)',
    'idea_not_found': 'Idée non trouvée',

    // Business form
    'new_business_idea': 'Nouvelle Idée Business',
    'sector': 'Secteur d\'activité *',
    'sector_hint': 'Ex: E-commerce, Services, SaaS...',
    'startup_budget': 'Budget de démarrage',
    'skills': 'Compétences disponibles',
    'skills_hint': 'Ex: Marketing, Développement, Design...',
    'time_available': 'Temps disponible',
    'location': 'Localisation',
    'extra_prefs': 'Préférences additionnelles',
    'recurring_model': 'Modèle récurrent (abonnements)',
    'scalable': 'Scalable rapidement',
    'low_competition': 'Peu de concurrence',
    'generate_business': '💼 Générer des Idées Business',
    'budget_small': 'Petit (<5K€)',
    'budget_medium': 'Moyen (5-20K€)',
    'budget_high': 'Élevé (>20K€)',
    'time_side': 'Side Hustle',
    'time_full': 'Full-time',
    'loc_online': 'En ligne',
    'loc_local': 'Local',
    'loc_hybrid': 'Hybride',

    // Product form
    'new_product_idea': 'Nouvelle Idée Produit',
    'product_category': 'Catégorie du produit *',
    'product_niche_hint': 'Ex: Productivité, Santé, Éducation...',
    'estimated_budget': 'Budget production estimé',
    'generate_product': '🛍️ Générer des Idées Produit',
    'cat_physical': 'Physique',
    'cat_digital': 'Digital',
    'cat_service': 'Service',

    // Slogans form
    'new_slogans': 'Slogans & Noms',
    'product_brand': 'Nom du produit / marque *',
    'brand_hint': 'Ex: FocusFlow',
    'sector_activity': 'Secteur d\'activité *',
    'sector_activity_hint': 'Ex: Application mobile productivité',
    'brand_values': 'Valeurs de la marque (3-5 mots-clés)',
    'values_hint': 'Ex: Innovation, Simplicité, Efficacité',
    'target_audience_short': 'Public cible',
    'target_hint': 'Ex: Professionnels 25-40 ans',
    'tone_wanted': 'Ton souhaité',
    'language': 'Langue',
    'generate_slogans': '✍️ Générer 10 Slogans',
    'tone_serious': 'Sérieux',
    'tone_funny': 'Humoristique',
    'tone_pro': 'Professionnel',
    'tone_offbeat': 'Décalé',

    // Results
    'ideas_generated': 'idées générées',
    'save': 'Sauvegarder',
    'copy': 'Copier',

    // Idea detail
    'share': 'Partager',
    'why_it_works': 'Pourquoi ça marche',
    'why_content': 'Cette idée fonctionne car elle montre une transformation claire avant/après qui capte l\'attention. Le format rapide avec transitions est parfait pour TikTok et génère de l\'engagement.',
    'execution_plan': 'Plan d\'exécution',
    'suggested_hashtags': 'Hashtags suggérés',
    'save_idea': '❤️ Sauvegarder',
    'create_variations': '🔁 Créer variations',

    // Credits
    'shop': 'Boutique',
    'credits_shop': 'Boutique Crédits',
    'buy_credits_subtitle': 'Achetez des crédits pour générer des idées',
    'popular': 'POPULAIRE',
    'buy': 'Acheter',

    // Payment
    'payment': 'Paiement',
    'secure_encrypted': 'Sécurisé & Crypté',
    'selected_pack': 'Pack sélectionné',
    'credits': 'Crédits',
    'total': 'Total',
    'payment_method': 'Méthode de paiement',
    'card': 'Carte Bancaire',
    'card_subtitle': 'Visa, Mastercard, Amex',
    'apple_google_pay': 'Apple Pay / Google Pay',
    'fast_payment': 'Paiement rapide',
    'paypal': 'PayPal',
    'paypal_subtitle': 'Compte PayPal',
    'card_number': 'Numéro de carte',
    'card_number_hint': '1234 5678 9012 3456',
    'name_on_card': 'Nom sur la carte',
    'name_hint': 'Mohamed Ali',
    'expiry': 'Expiration',
    'expiry_hint': 'MM/YY',
    'cvv': 'CVV',
    'cvv_hint': '123',
    'confirm_payment': 'Confirmer le paiement',
    'secure_ssl': 'Paiement sécurisé SSL 256-bit',

    // Profile
    'preferences': 'Préférences',
    'dark_mode': 'Mode sombre',
    'daily_reminder': 'Daily idea reminder',
    'language_label': 'Langue',
    'french': 'Français',
    'english': 'English',
    'content': 'Contenu',
    'export_ideas': 'Export ideas (PDF)',
    'full_history': 'Historique complet',
    'support': 'Support',
    'rate_app': 'Rate app',
    'feedback': 'Feedback',
    'credits_shop_profile': 'Boutique Crédits',
    'sign_out': 'Déconnexion',
    'delete_account': 'Supprimer le compte',
    'delete_account_confirm_title': 'Supprimer le compte ?',
    'delete_account_confirm_message': 'Un code de vérification sera envoyé à votre adresse email pour confirmer la suppression. Cette action est irréversible.',
    'delete_account_send_code': 'Envoyer le code',
    'delete_account_enter_code_title': 'Confirmer la suppression',
    'delete_account_enter_code_message': 'Entrez le code à 6 chiffres envoyé à',
    'delete_account_confirm_button': 'Supprimer définitivement',
    'delete_account_code_sent': 'Code envoyé à votre email.',
    'cancel': 'Annuler',
    'account': 'Compte',
    'personal_information': 'Information Personnel',
    'edit_profile': 'Modifier le profil',
    'save_changes': 'Enregistrer les modifications',
    'full_name': 'Nom complet',
    'full_name_hint': 'Votre nom',
    'phone': 'Téléphone',
    'phone_hint': '+33 6 12 34 56 78',
    'bio': 'Bio',
    'bio_hint': 'Parlez-nous de vous...',
    'profile_updated': 'Profil mis à jour avec succès',
    'user': 'Utilisateur',
    'email_example': 'email@exemple.com',

    // Library
    'my_ideas': 'Mes Idées',
    'all_types': 'Tous types',
    'all': 'Toutes',
    'in_progress': 'En cours',
    'done_count': 'Terminées',
    'created_on': 'Créée le',
    'type_video': '🎬 Vidéos',
    'type_business': '💼 Business',
    'type_product': '🎁 Produits',
    'type_slogans': '✨ Slogans',
    'ideas_saved_count': '47 idées sauvegardées',
    'view': '👁️ Voir',
    'edit': '✏️ Éditer',
    'share_action': '📤 Partager',
    'remove': 'Retirer',
    'today': 'Aujourd\'hui',
    'filter_product': 'Produit',

    // Trends
    'current_trends': 'Tendances Actuelles',
    'see_all_trends': '📊 Voir toutes les tendances',
    'trends_match_profile': '5 nouvelles tendances correspondent à votre profil !',
    'rising_trends': '🔥 Tendances Montantes',
    'popular_now': '⭐ Populaires Maintenant',
    'evergreen_potential': '🌿 Potentiel Evergreen',
    'growth': 'Croissance',
    'peak_interest': 'Pic d\'intérêt actuel',
    'stable_interest': 'Intérêt stable',
    'for_you': 'Pour vous',
    'video_tab': 'Vidéo',
    'business_tab': 'Business',
    'products_tab': 'Produits',

    // Persona Onboarding
    'persona_tagline': 'PERSONNALISONS TON EXPÉRIENCE',
    'persona_progress': 'PROGRESSION',
    'persona_back': '← RETOUR',
    'persona_next': 'SUIVANT →',
    'persona_finish': '✓ TERMINER',
    'persona_success_title': 'Profil Complété !',
    'persona_success_subtitle': 'Ton profil est maintenant configuré.\nPrêt à générer des idées de contenu personnalisées ?',
    'persona_success_button': 'COMMENCER 🚀',

    // Persona Questions
    'persona_q1_title': 'Ton profil',
    'persona_q1_subtitle': 'Quel type de créateur es-tu ?',
    'persona_q2_title': 'Ton objectif principal',
    'persona_q2_subtitle': 'Que cherches-tu à accomplir ?',
    'persona_q3_title': 'Ta niche principale',
    'persona_q3_subtitle': 'Dans quel domaine crées-tu du contenu ?',
    'persona_q4_title': 'Ta plateforme principale',
    'persona_q4_subtitle': 'Où publies-tu principalement ?',
    'persona_q5_title': 'Tes plateformes fréquentes',
    'persona_q5_subtitle': 'Sélectionne toutes celles que tu utilises',
    'persona_q6_title': 'Ton style de contenu',
    'persona_q6_subtitle': 'Comment crées-tu tes vidéos ?',
    'persona_q7_title': 'Ton audience principale',
    'persona_q7_subtitle': 'À qui t\'adresses-tu principalement ?',
    'persona_q8_title': 'Âge de ton audience',
    'persona_q8_subtitle': 'Quelle tranche d\'âge cibles-tu ?',
    'persona_q9_title': 'Ton ton préféré',
    'persona_q9_subtitle': 'Quel ton utilises-tu ?',
    'persona_q10_title': 'Langue & Call-to-Action',
    'persona_q10_subtitle': 'Dernière étape !',
    'persona_language_label': 'LANGUE PRINCIPALE',
    'persona_cta_label': 'CALL-TO-ACTION PRÉFÉRÉ',

    // Persona profile section
    'persona_section_title': 'Mon Persona',
    'persona_profile_label': 'Profil',
    'persona_goal_label': 'Objectif',
    'persona_niches_label': 'Niches',
    'persona_platform_label': 'Plateforme',
    'persona_platforms_label': 'Plateformes',
    'persona_styles_label': 'Styles',
    'persona_tone_label': 'Ton',
    'persona_audiences_label': 'Audience',
    'persona_age_label': 'Tranche d\'age',
    'persona_lang_label': 'Langue',
    'persona_ctas_label': 'CTA',
    'persona_edit_button': 'Modifier mon persona',
    'persona_not_configured': 'Persona non configuré',
    'persona_setup_button': 'Configurer mon persona',
    'persona_loading': 'Chargement...',
    'persona_retake_quiz': 'Reprendre le quiz complet',
    'persona_confirm_selection': 'Confirmer',
    'persona_min_one_required': 'Sélectionnez au moins un élément',
    'persona_update_success': 'Persona mis à jour',

    // Navigation (sidebar + bottom nav)
    'nav_main': 'PRINCIPAL',
    'nav_dashboard': 'Accueil',
    'nav_brands': 'Marques',
    'nav_calendar': 'Calendrier',
    'nav_projects': 'Projets',
    'nav_plans': 'Plans',
    'nav_insights': 'Insights',
    'nav_tools': 'OUTILS',
    'nav_account': 'COMPTE',
    'nav_idea_gen': 'Générateur d\'idées',
    'nav_new_plan': 'Nouveau Plan',
    'nav_no_plans': 'Aucun plan',

    // Shared actions
    'delete': 'Supprimer',
    'retry': 'Réessayer',

    // Plan flow
    'plan_new_project': 'Planifier un projet',
    'plan_no_brands_title': 'Aucune marque',
    'plan_no_brands_desc': 'Créez d\'abord une marque, puis revenez planifier.',
    'plan_create_brand': 'Créer une marque',
    'plan_choose_brand': 'Choisir une marque',
    'plan_choose_brand_desc': 'Pour quelle marque planifions-nous ?',
    'plan_details_title': 'Détails du plan',
    'plan_details_desc': 'Nommez votre plan et définissez le calendrier.',
    'plan_name_label': 'NOM DU PLAN',
    'plan_name_hint': 'ex. Campagne Printemps',
    'plan_start_date': 'DATE DE DÉBUT',
    'plan_duration_label': 'DURÉE',
    'plan_posts_week_label': 'POSTS PAR SEMAINE',
    'plan_weeks_suffix': 'semaines',
    'plan_campaign_obj': 'Objectif de campagne',
    'plan_obj_desc': 'Quel est l\'objectif principal de ce plan ?',
    'plan_generating_title': 'Gemini construit votre plan…',
    'plan_creating_title': 'Création du plan…',
    'plan_analysing_desc': 'Analyse de la marque, du mix et des objectifs.',
    'plan_gen_failed': 'Génération échouée',
    'plan_go_back': 'Retour',
    'plan_created_title': 'Plan créé !',
    'plan_view_approve': 'Voir et approuver le plan',
    'plan_regenerate': 'Régénérer le plan',
    'plan_continue': 'Continuer',
    'plan_generate_btn': 'Générer le plan ✨',
    'plan_back_btn': 'Retour',

    // Plans list
    'plans_title': 'Mes Plans',
    'plans_filter_all': 'Tous',
    'plans_filter_draft': 'Brouillon',
    'plans_filter_active': 'Actif',
    'plans_filter_completed': 'Terminé',
    'plans_all_brands': 'Toutes les marques',
    'plans_empty_title': 'Aucun plan',
    'plans_empty_desc': 'Générez votre premier plan de contenu IA.',
    'plans_create_btn': 'Créer un plan',
    'plans_load_error': 'Impossible de charger les plans',
    'plans_new_btn': 'Nouveau Plan',
    'plans_activate_schedule_title': 'Activer et planifier',
    'plans_activate_schedule_msg': 'Ceci va activer le plan et ajouter tous les posts au calendrier.',
    'plans_delete_title': 'Supprimer le plan',
    'plans_cannot_undone': 'Cette action est irréversible.',
    'plans_added_cal': 'Posts ajoutés au calendrier !',
    'plan_status_draft': 'Brouillon',
    'plan_status_active': 'Actif',
    'plan_status_completed': 'Terminé',

    // Plan detail
    'detail_phases_label': 'PHASES',
    'detail_no_phases': 'Aucune phase',
    'detail_no_phases_desc': 'Régénérez ce plan pour que Gemini construise la structure de contenu.',
    'detail_activate_btn': '⚡ Activer le plan',
    'detail_add_cal_btn': '📅 Ajouter au calendrier',
    'detail_regen_btn': '✨ Régénérer avec l\'IA',
    'detail_delete_btn': 'Supprimer le plan',
    'detail_regen_gemini': 'Gemini régénère…',
    'detail_processing': 'Traitement…',
    'detail_plan_activated': 'Plan activé !',
    'detail_edit_name': 'Modifier le nom',
    'detail_unknown_brand': 'Marque inconnue',
    'detail_regen_dialog_title': 'Régénérer le plan',
    'detail_regen_dialog_msg': 'Gemini va reconstruire toutes les phases et contenus.',
    'detail_regen_confirm': 'Régénérer ✨',
    'detail_duration_stat': 'Durée',
    'detail_frequency_stat': 'Fréquence',
    'detail_plan_name_label': 'Nom du plan',

    // Calendar
    'cal_smart_rotation': 'Rotation Intelligente',
    'cal_ai_spacing': 'Espacement IA actif — pas de promos consécutives',
    'cal_on': 'ON',
    'cal_all_brands': 'Toutes les marques',
    'cal_no_posts': 'Aucun post cette semaine',
    'cal_activate_plan': 'Activez un plan pour remplir votre calendrier',
    'cal_load_error': 'Impossible de charger le calendrier',

    // Insights
    'insights_title': 'Insights Stratégiques',
    'insights_subtitle': 'Analyse des 30 derniers jours',
    'insights_content_ratio': 'Ratio de contenu',
    'insights_alerts': 'Alertes stratégiques',
    'insights_content_types': 'Types de contenu',
    'insights_snapshot': 'Instantané Stratégique',
    'insights_health_scores': 'Scores de Santé',
    'insights_content_health': 'Santé du Contenu',
    'insights_audience_match': 'Correspondance Audience',
    'insights_conversion_pot': 'Potentiel de Conversion',
    'insights_content_dist': 'Distribution du Contenu',
    'insights_risks': 'Indicateurs de Risque',
    'insights_ai_actions': 'Actions IA Recommandées',

    // Brand workspace
    'brand_ws_overview': 'Aperçu',
    'brand_ws_audience': 'Audience',
    'brand_ws_pillars': 'Piliers de contenu',
    'brand_ws_identity': 'Identité',
    'brand_ws_platforms': 'Plateformes',
    'brand_ws_tone': 'Ton de la marque',
    'brand_ws_no_platforms': 'Aucune plateforme configurée.',
    'brand_ws_age_range': 'Tranche d\'âge',
    'brand_ws_gender': 'Genre',
    'brand_ws_interests': 'Centres d\'intérêt',
    'brand_ws_not_specified': 'Non spécifié',
    'brand_ws_no_interests': 'Aucun intérêt renseigné.',
    'brand_ws_no_pillars': 'Aucun pilier de contenu défini.',
    'brand_ws_edit_btn': 'Modifier la marque',

    // Brand suggestions
    'brand_suggestions_all_added': 'Toutes les suggestions déjà ajoutées !',
  };

  static const Map<String, String> _en = {
    'app_name': 'IdeaSpark',
    'splash_tagline': 'Generate · Test · Launch',

    'login': 'Login',
    'signup': 'Create an account',
    'email': 'Email',
    'email_hint': 'your@email.com',
    'password': 'Password',
    'password_hint': '••••••••',
    'confirm_password': 'Confirm password',
    'sign_in': 'Sign in',
    'sign_up': 'Sign up',
    'or': 'or',
    'continue_google': 'Continue with Google',
    'continue_facebook': 'Continue with Facebook',
    'signup_google': 'Sign up with Google',
    'signup_facebook': 'Sign up with Facebook',
    'no_account': 'No account? ',
    'has_account': 'Already have an account? ',
    'verify_email_title': 'Verify your email',
    'verify_email_sent': 'A 6-digit code was sent to',
    'verify_code_hint': 'Verification code',
    'forgot_password': 'Forgot password',
    'forgot_password_enter_email': 'Enter your email to receive a reset code.',
    'forgot_password_send_code': 'Send code',
    'forgot_password_code_sent': 'Code sent to your email.',
    'forgot_password_code_sent_to': 'A code was sent to',
    'reset_password': 'Reset password',
    'password_reset_success': 'Password updated. Sign in with your new password.',
    'back_to_login': 'Back to login',
    'new_password': 'New password',
    'current_password': 'Current password',
    'change_password': 'Change password',
    'change_password_title': 'Change password',
    'change_password_confirm': 'Save',
    'change_password_success': 'Password updated.',
    'passwords_do_not_match': 'Passwords do not match.',
    'verify_button': 'Verify',
    'resend_code': 'Resend code',

    'onboarding_title_1': 'Instant ideas',
    'onboarding_desc_1': 'Smart generator to create business, video, product and slogan concepts in seconds.',
    'onboarding_title_2': 'Filter by niche and audience',
    'onboarding_desc_2': 'Customize each generation for your target market, audience and goals.',
    'onboarding_title_3': 'Save and re-generate',
    'onboarding_desc_3': 'Keep your best ideas, create variations and share with your team.',
    'start': 'GET STARTED',
    'continue': 'CONTINUE',
    'skip': 'Skip',

    'hello': 'Hello 👋',
    'what_idea_type': 'What type of idea do you want to generate?',
    'trends': 'Trends',
    'see_all': 'See all',
    'library_saved': 'Library · My saved ideas',
    'nav_home': 'Home',
    'nav_favorites': 'Favorites',
    'nav_history': 'History',
    'nav_profile': 'Profile',

    'gen_business': 'Business Ideas',
    'gen_video': 'Video Ideas',
    'gen_product': 'Product Ideas',
    'gen_slogans': 'Slogans & Names',

    'settings': 'Settings',
    'tell_us_what': 'Tell us what to generate',
    'type': 'Type',
    'niche': 'Niche',
    'niche_hint': 'E.g. Fitness, Beauty, Tech...',
    'target_audience': 'Target audience',
    'platform': 'Platform',
    'tone_style': 'Tone / Style',
    'creativity_level': 'Creativity level',
    'realistic': 'Realistic',
    'creative': 'Creative',
    'generate_10': 'Generate 10 ideas',
    'surprise_me': 'Surprise me ✨',

    'opt_étudiants': 'Students',
    'opt_mamans': 'Moms',
    'opt_entrepreneurs': 'Entrepreneurs',
    'opt_freelancers': 'Freelancers',
    'opt_tiktok': 'TikTok',
    'opt_reels': 'Reels',
    'opt_youtube': 'YouTube',
    'opt_shorts': 'Shorts',
    'opt_viral': 'Viral',
    'opt_premium': 'Premium',
    'opt_fun': 'Fun',
    'opt_sérieux': 'Serious',
    'filter_all': 'All',
    'filter_viral': 'Viral',
    'filter_realistic': 'Realistic',
    'filter_short': 'Short',
    'filter_business': 'Business',
    'filter_video': 'Video',
    'favorites_title': 'Favorites',
    'history_title': 'History',

    'new_video_idea': 'New Video Idea',
    'theme_niche': 'Theme / Niche *',
    'theme_hint': 'E.g. Fitness, Tech, Cooking...',
    'target_platform': 'Target platform',
    'duration': 'Duration',
    'keywords_optional': 'Keywords (optional)',
    'keywords_hint': 'Separate with commas',
    'generate_ideas': '✨ Generate Ideas',
    'platform_youtube': 'YouTube',
    'platform_tiktok': 'TikTok',
    'platform_reels': 'Instagram Reels',
    'platform_shorts': 'YouTube Shorts',
    'duration_short': 'Short (<1min)',
    'duration_medium': 'Medium (3-5min)',
    'duration_long': 'Long (10min+)',
    'tone_educational': 'Educational',
    'tone_entertaining': 'Entertaining',
    'tone_inspiring': 'Inspiring',
    'tone_commercial': 'Commercial',

    // Gemini 2.0 Features
    'smart_analysis': 'Smart Analysis',
    'image_picker_desc': 'Take a photo of your product to automatically fill the fields below.',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'analyzing': 'Analyzing...',
    'refine_hint': 'Refine this idea...',
    'remaining_tries': 'tries remaining',
    'limit_reached': 'Refinement limit reached',
    'approve': 'Approve',
    'version': 'Version',
    'version_history': 'Version History',
    'favorite': 'Favorite',
    'favorited': 'Favorited ✨',
    'suggested_locations': 'SUGGESTED FILMING LOCATIONS',
    'refine_error': 'Refinement failed. Please try again.',
    'approve_error': 'Approval failed.',
    'refine_limit_error': 'Maximum refinements reached (3)',
    'idea_not_found': 'Idea not found',

    'new_business_idea': 'New Business Idea',
    'sector': 'Business sector *',
    'sector_hint': 'E.g. E-commerce, Services, SaaS...',
    'startup_budget': 'Startup budget',
    'skills': 'Available skills',
    'skills_hint': 'E.g. Marketing, Development, Design...',
    'time_available': 'Time available',
    'location': 'Location',
    'extra_prefs': 'Additional preferences',
    'recurring_model': 'Recurring model (subscriptions)',
    'scalable': 'Quickly scalable',
    'low_competition': 'Low competition',
    'generate_business': '💼 Generate Business Ideas',
    'budget_small': 'Small (<5K€)',
    'budget_medium': 'Medium (5-20K€)',
    'budget_high': 'High (>20K€)',
    'time_side': 'Side Hustle',
    'time_full': 'Full-time',
    'loc_online': 'Online',
    'loc_local': 'Local',
    'loc_hybrid': 'Hybrid',

    'new_product_idea': 'New Product Idea',
    'product_category': 'Product category *',
    'product_niche_hint': 'E.g. Productivity, Health, Education...',
    'estimated_budget': 'Estimated production budget',
    'generate_product': '🛍️ Generate Product Ideas',
    'cat_physical': 'Physical',
    'cat_digital': 'Digital',
    'cat_service': 'Service',

    'new_slogans': 'Slogans & Names',
    'product_brand': 'Product / brand name *',
    'brand_hint': 'E.g. FocusFlow',
    'sector_activity': 'Business sector *',
    'sector_activity_hint': 'E.g. Productivity mobile app',
    'brand_values': 'Brand values (3-5 keywords)',
    'values_hint': 'E.g. Innovation, Simplicity, Efficiency',
    'target_audience_short': 'Target audience',
    'target_hint': 'E.g. Professionals 25-40',
    'tone_wanted': 'Desired tone',
    'language': 'Language',
    'generate_slogans': '✍️ Generate 10 Slogans',
    'tone_serious': 'Serious',
    'tone_funny': 'Funny',
    'tone_pro': 'Professional',
    'tone_offbeat': 'Offbeat',

    'ideas_generated': 'ideas generated',
    'save': 'Save',
    'copy': 'Copy',

    'share': 'Share',
    'why_it_works': 'Why it works',
    'why_content': 'This idea works because it shows a clear before/after transformation that catches attention. The fast format with transitions is perfect for TikTok and drives engagement.',
    'execution_plan': 'Execution plan',
    'suggested_hashtags': 'Suggested hashtags',
    'save_idea': '❤️ Save',
    'create_variations': '🔁 Create variations',

    'shop': 'Shop',
    'credits_shop': 'Credits Shop',
    'buy_credits_subtitle': 'Buy credits to generate ideas',
    'popular': 'POPULAR',
    'buy': 'Buy',

    'payment': 'Payment',
    'secure_encrypted': 'Secure & Encrypted',
    'selected_pack': 'Selected pack',
    'credits': 'Credits',
    'total': 'Total',
    'payment_method': 'Payment method',
    'card': 'Credit Card',
    'card_subtitle': 'Visa, Mastercard, Amex',
    'apple_google_pay': 'Apple Pay / Google Pay',
    'fast_payment': 'Fast payment',
    'paypal': 'PayPal',
    'paypal_subtitle': 'PayPal account',
    'card_number': 'Card number',
    'card_number_hint': '1234 5678 9012 3456',
    'name_on_card': 'Name on card',
    'name_hint': 'John Doe',
    'expiry': 'Expiration',
    'expiry_hint': 'MM/YY',
    'cvv': 'CVV',
    'cvv_hint': '123',
    'confirm_payment': 'Confirm payment',
    'secure_ssl': 'Secure payment SSL 256-bit',

    'preferences': 'Preferences',
    'dark_mode': 'Dark mode',
    'daily_reminder': 'Daily idea reminder',
    'language_label': 'Language',
    'french': 'Français',
    'english': 'English',
    'content': 'Content',
    'export_ideas': 'Export ideas (PDF)',
    'full_history': 'Full history',
    'support': 'Support',
    'rate_app': 'Rate app',
    'feedback': 'Feedback',
    'credits_shop_profile': 'Credits Shop',
    'sign_out': 'Sign out',
    'delete_account': 'Delete account',
    'delete_account_confirm_title': 'Delete account?',
    'delete_account_confirm_message': 'A verification code will be sent to your email to confirm deletion. This action cannot be undone.',
    'delete_account_send_code': 'Send code',
    'delete_account_enter_code_title': 'Confirm deletion',
    'delete_account_enter_code_message': 'Enter the 6-digit code sent to',
    'delete_account_confirm_button': 'Delete permanently',
    'delete_account_code_sent': 'Code sent to your email.',
    'cancel': 'Cancel',
    'account': 'Account',
    'personal_information': 'Personal Information',
    'edit_profile': 'Edit Profile',
    'save_changes': 'Save changes',
    'full_name': 'Full name',
    'full_name_hint': 'Your name',
    'phone': 'Phone',
    'phone_hint': '+1 234 567 8900',
    'bio': 'Bio',
    'bio_hint': 'Tell us about yourself...',
    'profile_updated': 'Profile updated successfully',
    'user': 'User',
    'email_example': 'email@example.com',

    'my_ideas': 'My Ideas',
    'all_types': 'All types',
    'all': 'All',
    'in_progress': 'In progress',
    'done_count': 'Done',
    'created_on': 'Created on',
    'type_video': '🎬 Videos',
    'type_business': '💼 Business',
    'type_product': '🎁 Products',
    'type_slogans': '✨ Slogans',
    'ideas_saved_count': '47 saved ideas',
    'view': '👁️ View',
    'edit': '✏️ Edit',
    'share_action': '📤 Share',
    'remove': 'Remove',
    'today': 'Today',
    'filter_product': 'Product',

    'current_trends': 'Current Trends',
    'see_all_trends': '📊 See all trends',
    'trends_match_profile': '5 new trends match your profile!',
    'rising_trends': '🔥 Rising Trends',
    'popular_now': '⭐ Popular Now',
    'evergreen_potential': '🌿 Evergreen Potential',
    'growth': 'Growth',
    'peak_interest': 'Peak interest',
    'stable_interest': 'Stable interest',
    'for_you': 'For you',
    'video_tab': 'Video',
    'business_tab': 'Business',
    'products_tab': 'Products',

    // Persona Onboarding
    'persona_tagline': 'LET\'S PERSONALIZE YOUR EXPERIENCE',
    'persona_progress': 'PROGRESS',
    'persona_back': '← BACK',
    'persona_next': 'NEXT →',
    'persona_finish': '✓ FINISH',
    'persona_success_title': 'Profile Completed!',
    'persona_success_subtitle': 'Your profile is now configured.\nReady to generate personalized content ideas?',
    'persona_success_button': 'GET STARTED 🚀',

    // Persona Questions
    'persona_q1_title': 'Your profile',
    'persona_q1_subtitle': 'What type of creator are you?',
    'persona_q2_title': 'Your main goal',
    'persona_q2_subtitle': 'What are you looking to achieve?',
    'persona_q3_title': 'Your main niche',
    'persona_q3_subtitle': 'What domain do you create content in?',
    'persona_q4_title': 'Your main platform',
    'persona_q4_subtitle': 'Where do you mainly publish?',
    'persona_q5_title': 'Your frequent platforms',
    'persona_q5_subtitle': 'Select all that you use',
    'persona_q6_title': 'Your content style',
    'persona_q6_subtitle': 'How do you create your videos?',
    'persona_q7_title': 'Your main audience',
    'persona_q7_subtitle': 'Who do you mainly target?',
    'persona_q8_title': 'Your audience age',
    'persona_q8_subtitle': 'What age range do you target?',
    'persona_q9_title': 'Your preferred tone',
    'persona_q9_subtitle': 'What tone do you use?',
    'persona_q10_title': 'Language & Call-to-Action',
    'persona_q10_subtitle': 'Last step!',
    'persona_language_label': 'MAIN LANGUAGE',
    'persona_cta_label': 'PREFERRED CALL-TO-ACTION',

    // Persona profile section
    'persona_section_title': 'My Persona',
    'persona_profile_label': 'Profile',
    'persona_goal_label': 'Goal',
    'persona_niches_label': 'Niches',
    'persona_platform_label': 'Platform',
    'persona_platforms_label': 'Platforms',
    'persona_styles_label': 'Styles',
    'persona_tone_label': 'Tone',
    'persona_audiences_label': 'Audience',
    'persona_age_label': 'Age range',
    'persona_lang_label': 'Language',
    'persona_ctas_label': 'CTA',
    'persona_edit_button': 'Edit my persona',
    'persona_not_configured': 'Persona not configured',
    'persona_setup_button': 'Set up my persona',
    'persona_loading': 'Loading...',
    'persona_retake_quiz': 'Retake full quiz',
    'persona_confirm_selection': 'Confirm',
    'persona_min_one_required': 'Select at least one item',
    'persona_update_success': 'Persona updated',

    // Navigation (sidebar + bottom nav)
    'nav_main': 'MAIN',
    'nav_dashboard': 'Dashboard',
    'nav_brands': 'Brands',
    'nav_calendar': 'Calendar',
    'nav_projects': 'Projects',
    'nav_plans': 'Plans',
    'nav_insights': 'Insights',
    'nav_tools': 'Tools',
    'nav_account': 'Account',
    'nav_idea_gen': 'Idea Generator',
    'nav_new_plan': 'New Plan',
    'nav_no_plans': 'No plans yet',

    // Shared actions
    'delete': 'Delete',
    'retry': 'Retry',

    // Plan flow
    'plan_new_project': 'Plan New Project',
    'plan_no_brands_title': 'No brands yet',
    'plan_no_brands_desc': 'Create a brand first, then come back to plan.',
    'plan_create_brand': 'Create Brand',
    'plan_choose_brand': 'Choose Brand',
    'plan_choose_brand_desc': 'Which brand are we planning for?',
    'plan_details_title': 'Plan Details',
    'plan_details_desc': 'Name your plan and set the timeline.',
    'plan_name_label': 'PLAN NAME',
    'plan_name_hint': 'e.g. Spring Launch Campaign',
    'plan_start_date': 'START DATE',
    'plan_duration_label': 'DURATION',
    'plan_posts_week_label': 'POSTS PER WEEK',
    'plan_weeks_suffix': 'weeks',
    'plan_campaign_obj': 'Campaign Objective',
    'plan_obj_desc': 'What is the main goal of this plan?',
    'plan_generating_title': 'Gemini is building your plan…',
    'plan_creating_title': 'Creating plan…',
    'plan_analysing_desc': 'Analysing brand, mix, and objectives.',
    'plan_gen_failed': 'Generation failed',
    'plan_go_back': 'Go Back',
    'plan_created_title': 'Plan Created!',
    'plan_view_approve': 'View & Approve Plan',
    'plan_regenerate': 'Regenerate Plan',
    'plan_continue': 'Continue',
    'plan_generate_btn': 'Generate Plan ✨',
    'plan_back_btn': 'Back',

    // Plans list
    'plans_title': 'My Plans',
    'plans_filter_all': 'All',
    'plans_filter_draft': 'Draft',
    'plans_filter_active': 'Active',
    'plans_filter_completed': 'Completed',
    'plans_all_brands': 'All Brands',
    'plans_empty_title': 'No plans yet',
    'plans_empty_desc': 'Generate your first AI-powered content plan.',
    'plans_create_btn': 'Create Plan',
    'plans_load_error': 'Could not load plans',
    'plans_new_btn': 'New Plan',
    'plans_activate_schedule_title': 'Activate & Schedule',
    'plans_activate_schedule_msg': 'This will activate the plan and add all posts to your calendar.',
    'plans_delete_title': 'Delete Plan',
    'plans_cannot_undone': 'This cannot be undone.',
    'plans_added_cal': 'Posts added to calendar!',
    'plan_status_draft': 'Draft',
    'plan_status_active': 'Active',
    'plan_status_completed': 'Completed',

    // Plan detail
    'detail_phases_label': 'PHASES',
    'detail_no_phases': 'No phases yet',
    'detail_no_phases_desc': 'Regenerate this plan to let Gemini build the content structure.',
    'detail_activate_btn': '⚡ Activate Plan',
    'detail_add_cal_btn': '📅 Add to Calendar',
    'detail_regen_btn': '✨ Regenerate with AI',
    'detail_delete_btn': 'Delete Plan',
    'detail_regen_gemini': 'Gemini is regenerating…',
    'detail_processing': 'Processing…',
    'detail_plan_activated': 'Plan activated!',
    'detail_edit_name': 'Edit Plan Name',
    'detail_unknown_brand': 'Unknown Brand',
    'detail_regen_dialog_title': 'Regenerate Plan',
    'detail_regen_dialog_msg': 'Gemini will rebuild all phases and content blocks.',
    'detail_regen_confirm': 'Regenerate ✨',
    'detail_duration_stat': 'Duration',
    'detail_frequency_stat': 'Frequency',
    'detail_plan_name_label': 'Plan name',

    // Calendar
    'cal_smart_rotation': 'Smart Rotation',
    'cal_ai_spacing': 'AI spacing is active — no back-to-back promos',
    'cal_on': 'ON',
    'cal_all_brands': 'All Brands',
    'cal_no_posts': 'No posts this week',
    'cal_activate_plan': 'Activate a plan to populate your calendar',
    'cal_load_error': 'Could not load calendar',

    // Insights
    'insights_title': 'Strategic Insights',
    'insights_subtitle': 'Analysis for last 30 days',
    'insights_content_ratio': 'Content Ratio',
    'insights_alerts': 'Strategic Alerts',
    'insights_content_types': 'Content Types',
    'insights_snapshot': 'Strategic Snapshot',
    'insights_health_scores': 'Health Scores',
    'insights_content_health': 'Content Health',
    'insights_audience_match': 'Audience Match',
    'insights_conversion_pot': 'Conversion Potential',
    'insights_content_dist': 'Content Distribution',
    'insights_risks': 'Risk Indicators',
    'insights_ai_actions': 'AI Recommended Actions',

    // Brand workspace
    'brand_ws_overview': 'Overview',
    'brand_ws_audience': 'Audience',
    'brand_ws_pillars': 'Content Pillars',
    'brand_ws_identity': 'Identity',
    'brand_ws_platforms': 'Platforms',
    'brand_ws_tone': 'Brand Tone',
    'brand_ws_no_platforms': 'No platforms configured.',
    'brand_ws_age_range': 'Age Range',
    'brand_ws_gender': 'Gender',
    'brand_ws_interests': 'Interests',
    'brand_ws_not_specified': 'Not specified',
    'brand_ws_no_interests': 'No interests listed.',
    'brand_ws_no_pillars': 'No content pillars defined.',
    'brand_ws_edit_btn': 'Edit Brand',

    // Brand suggestions
    'brand_suggestions_all_added': 'All suggestions already added!',
  };

  /// Option values displayed in criteria/filters (value from VM -> translated).
  static const Map<String, Map<String, String>> _optionEn = {
    'audience': {'Étudiants': 'Students', 'Mamans': 'Moms', 'Entrepreneurs': 'Entrepreneurs', 'Freelancers': 'Freelancers'},
    'platform': {'TikTok': 'TikTok', 'Reels': 'Reels', 'YouTube': 'YouTube', 'Shorts': 'Shorts'},
    'tone': {'Viral': 'Viral', 'Premium': 'Premium', 'Fun': 'Fun', 'Sérieux': 'Serious'},
    'filter': {'Tous': 'All', 'Viral': 'Viral', 'Réaliste': 'Realistic', 'Courtes': 'Short'},
  };

  static String translate(String key, String locale) {
    final map = locale == 'en' ? _en : _fr;
    return map[key] ?? _fr[key] ?? key;
  }

  static String translateOption(String locale, String category, String value) {
    if (locale != 'en') return value;
    final cat = _optionEn[category];
    return cat?[value] ?? value;
  }
}

extension AppLocalizationsExtension on BuildContext {
  String tr(String key) {
    final localeVm = read<LocaleViewModel>();
    return AppLocalizations.translate(key, localeVm.locale);
  }

  String trOption(String category, String value) {
    final localeVm = read<LocaleViewModel>();
    return AppLocalizations.translateOption(localeVm.locale, category, value);
  }
}
