// Mocks generated by Mockito 5.4.6 from annotations
// in ideaspark/test/view_models/saved_ideas_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ideaspark/models/video_generator_models.dart' as _i4;
import 'package:ideaspark/repositories/saved_ideas_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SavedVideoIdeasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSavedVideoIdeasRepository extends _i1.Mock
    implements _i2.SavedVideoIdeasRepository {
  MockSavedVideoIdeasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveIdea(_i4.VideoIdea? idea) =>
      (super.noSuchMethod(
            Invocation.method(#saveIdea, [idea]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.VideoIdea>> getSavedIdeas() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedIdeas, []),
            returnValue: _i3.Future<List<_i4.VideoIdea>>.value(
              <_i4.VideoIdea>[],
            ),
          )
          as _i3.Future<List<_i4.VideoIdea>>);

  @override
  _i3.Future<void> removeIdea(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeIdea, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAll() =>
      (super.noSuchMethod(
            Invocation.method(#clearAll, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
